import pytest
from fastapi.testclient import TestClient

from ifc_compliance_mvd import api as api_module
from ifc_compliance_mvd.engine import MODEL_ID
from ifc_compliance_mvd.storage import ComplianceStore

client = TestClient(api_module.app)


@pytest.fixture(autouse=True)
def isolated_api_store(tmp_path, monkeypatch):
    store = ComplianceStore(tmp_path / "api-runtime" / "compliance.db")
    store.seed_fixture(
        model_id=MODEL_ID,
        model_name="IBC egress controlled fixture",
        schema_version=api_module.engine.model.schema,
        source="reproducibly generated by scripts/generate_fixture.py",
        model_path=api_module.engine.model_path,
        element_count=len(api_module.engine.elements),
    )
    monkeypatch.setattr(api_module, "store", store)


def test_health_and_models():
    health = client.get("/api/health")
    assert health.status_code == 200
    assert health.json()["rule_count"] == 3
    assert health.json()["element_count"] == 10
    assert health.json()["storage"]["schema_version"] == 2
    assert client.get("/api/models").json()[0]["schema"] == "IFC4"
    assert client.get("/api/projects").json()[0]["model_count"] == 1


def test_rule_to_elements_and_element_to_rules_are_bidirectional():
    rule_id = "IBC2021-1010.1.1-WIDTH"
    rule_elements = client.get(f"/api/rules/{rule_id}/elements").json()
    assert len(rule_elements) == 5
    guid = rule_elements[0]["global_id"]
    element_rules = client.get(f"/api/elements/{guid}/rules").json()
    assert rule_id in {rule["rule_id"] for rule in element_rules}
    assert all(rule["result"]["element_guid"] == guid for rule in element_rules)


def test_scene_is_guid_addressable_and_contains_real_geometry():
    scene = client.get("/api/scene").json()
    assert len(scene["elements"]) == 10
    assert len({element["global_id"] for element in scene["elements"]}) == 10
    geometries = [element["geometry"] for element in scene["elements"]]
    assert all(geometry["positions"] and geometry["indices"] for geometry in geometries)
    assert sum(geometry["placeholder"] for geometry in geometries) == 1
    assert all(element["spatial_path"] for element in scene["elements"])
    assert {
        node["ifc_class"]
        for node in scene["elements"][0]["spatial_path"]
    } >= {"IfcProject", "IfcSite", "IfcBuilding", "IfcBuildingStorey"}


def test_check_endpoint_is_deterministic_and_structured():
    first = client.post("/api/checks/run")
    second = client.post("/api/checks/run")
    assert first.status_code == second.status_code == 200
    assert first.json()["execution_id"] == second.json()["execution_id"]
    assert first.json()["run_id"] != second.json()["run_id"]
    assert first.json()["results"] == second.json()["results"]
    assert first.json()["status_counts"] == {
        "FAIL": 3,
        "NOT_APPLICABLE": 3,
        "NOT_CHECKABLE": 3,
        "PASS": 6,
    }
    history = client.get("/api/check-runs", params={"limit": 2}).json()
    assert history["total"] >= 2
    assert len(history["items"]) == 2
    comparison = client.get(
        f"/api/check-runs/{first.json()['run_id']}/compare/{second.json()['run_id']}"
    )
    assert comparison.json()["change_count"] == 0


def test_ego_graph_is_local_and_traceable():
    graph = client.get(
        "/api/graph/ego",
        params={"rule_id": "IBC2021-1003.2-EGRESS-HEIGHT"},
    ).json()
    kinds = {node["kind"] for node in graph["nodes"]}
    edge_types = {edge["type"] for edge in graph["edges"]}
    assert {"Clause", "Rule", "IfcElement", "ComplianceResult"} <= kinds
    assert {"FORMALIZED_AS", "APPLIES_TO", "PRODUCES", "EVIDENCED_BY"} <= edge_types


def test_unknown_ids_return_404():
    assert client.get("/api/rules/unknown").status_code == 404
    assert client.get("/api/elements/unknown/rules").status_code == 404


def test_natural_language_query_is_validated_executed_and_audited():
    response = client.post(
        "/api/query/execute",
        json={
            "utterance": "Which doors failed the clear width rule?",
            "locale": "en",
            "context": {},
        },
    )
    assert response.status_code == 200
    payload = response.json()
    assert payload["parsed"]["dsl"]["filters"] == {
        "rule_ids": ["IBC2021-1010.1.1-WIDTH"],
        "element_guids": [],
        "statuses": ["FAIL"],
        "ifc_classes": ["IfcDoor"],
        "storeys": [],
    }
    assert payload["total"] == 1
    assert payload["rows"][0]["element_guid"] == "3Pjm5RApzV1fY$bhkg16EY"
    history = client.get("/api/queries").json()
    assert history["total"] == 1
    assert history["items"][0]["query_id"] == payload["query_id"]


def test_ambiguous_or_malicious_query_fails_closed():
    response = client.post(
        "/api/query/execute",
        json={
            "utterance": "<script>fetch('/secrets')</script>; DROP TABLE results",
            "locale": "en",
        },
    )
    assert response.status_code == 200
    assert response.json()["parsed"]["executable"] is False
    assert response.json()["rows"] == []
    assert "NO_STRUCTURED_FILTERS" in response.json()["parsed"]["warnings"]

    oversized = client.post(
        "/api/query/execute",
        json={"utterance": "x" * 501, "locale": "en"},
    )
    assert oversized.status_code == 422


def test_openapi_describes_validated_query_contracts():
    schema = client.get("/openapi.json").json()
    for path in (
        "/api/query/parse",
        "/api/query/execute",
        "/api/query/execute-dsl",
        "/api/queries",
    ):
        assert path in schema["paths"]
    execute = schema["paths"]["/api/query/execute"]["post"]
    assert execute["requestBody"]["content"]["application/json"]["schema"]["$ref"].endswith(
        "NaturalLanguageQueryRequest"
    )
    assert execute["responses"]["200"]["content"]["application/json"]["schema"]["$ref"].endswith(
        "QueryExecutionResponse"
    )


def test_run_exports_cover_json_csv_html_and_bcf():
    run_id = client.post("/api/checks/run").json()["run_id"]
    expected = {
        "json": "application/json",
        "csv": "text/csv",
        "html": "text/html",
        "bcf": "application/zip",
    }
    for format_name, content_type in expected.items():
        response = client.get(
            f"/api/check-runs/{run_id}/export",
            params={"format": format_name, "locale": "zh-CN"},
        )
        assert response.status_code == 200
        assert response.headers["content-type"].startswith(content_type)
        assert response.headers["x-content-type-options"] == "nosniff"
        assert run_id in response.headers["content-disposition"]
        assert response.content
