from __future__ import annotations

from collections import Counter

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from .engine import CHECKER_VERSION, MODEL_ID, ComplianceEngine
from .graph import ego_graph
from .ifc_adapter import serialise_element
from .paths import FRONTEND_PATH
from .storage import ComplianceStore

app = FastAPI(
    title="IFC Bidirectional Compliance MVD",
    version=CHECKER_VERSION,
    description="Traceable exploration from structured IBC rules to IFC elements and back.",
)
engine = ComplianceEngine()
engine.run(persist=False)
store = ComplianceStore()
store.seed_fixture(
    model_id=MODEL_ID,
    model_name="IBC egress controlled fixture",
    schema_version=engine.model.schema,
    source="reproducibly generated by scripts/generate_fixture.py",
    model_path=engine.model_path,
    element_count=len(engine.elements),
)


def require_rule(rule_id: str) -> dict:
    try:
        return engine.rules[rule_id]
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown rule: {rule_id}") from error


def require_element(global_id: str):
    try:
        return engine.elements[global_id]
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown element: {global_id}") from error


@app.get("/api/health")
def health() -> dict:
    return {
        "status": "ok",
        "checker_version": CHECKER_VERSION,
        "model_loaded": True,
        "rule_count": len(engine.rules),
        "element_count": len(engine.elements),
        "storage": {
            "backend": "sqlite",
            "schema_version": store.schema_version(),
        },
    }


@app.get("/api/models")
def models() -> list[dict]:
    return [
        {
            **model,
            "schema": model["schema_version"],
        }
        for model in store.list_models()
    ]


@app.get("/api/projects")
def projects() -> list[dict]:
    return store.list_projects()


@app.get("/api/check-runs")
def check_runs(
    model_id: str | None = None,
    status: str | None = None,
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
) -> dict:
    return store.list_runs(
        model_id=model_id,
        status=status,
        limit=limit,
        offset=offset,
    )


@app.get("/api/check-runs/{run_id}")
def check_run(run_id: str) -> dict:
    item = store.get_run(run_id)
    if item is None:
        raise HTTPException(status_code=404, detail=f"Unknown check run: {run_id}")
    return item


@app.get("/api/check-runs/{base_run_id}/compare/{target_run_id}")
def compare_check_runs(base_run_id: str, target_run_id: str) -> dict:
    comparison = store.compare_runs(base_run_id, target_run_id)
    if comparison is None:
        raise HTTPException(status_code=404, detail="One or both check runs do not exist.")
    return comparison


@app.get("/api/models/{model_id}/elements/{global_id}")
def model_element(model_id: str, global_id: str) -> dict:
    if model_id != MODEL_ID:
        raise HTTPException(status_code=404, detail=f"Unknown model: {model_id}")
    return serialise_element(require_element(global_id), include_geometry=False)


@app.get("/api/rules")
def rules() -> list[dict]:
    results = engine.ensure_results()
    response = []
    for rule in engine.collection["rules"]:
        counts = Counter(
            result["status"] for result in results if result["rule_id"] == rule["rule_id"]
        )
        response.append({**rule, "status_counts": dict(counts)})
    return response


@app.get("/api/rules/{rule_id}")
def rule(rule_id: str) -> dict:
    selected = require_rule(rule_id)
    return {
        **selected,
        "results": [item for item in engine.ensure_results() if item["rule_id"] == rule_id],
    }


@app.get("/api/rules/{rule_id}/elements")
def rule_elements(rule_id: str) -> list[dict]:
    require_rule(rule_id)
    by_guid = engine.elements
    return [
        {
            **serialise_element(by_guid[result["element_guid"]]),
            "result": result,
        }
        for result in engine.ensure_results()
        if result["rule_id"] == rule_id
    ]


@app.get("/api/elements/{global_id}/rules")
def element_rules(global_id: str) -> list[dict]:
    require_element(global_id)
    return [
        {**engine.rules[result["rule_id"]], "result": result}
        for result in engine.ensure_results()
        if result["element_guid"] == global_id
    ]


@app.get("/api/elements/{global_id}/results")
def element_results(global_id: str) -> list[dict]:
    require_element(global_id)
    return [
        result
        for result in engine.ensure_results()
        if result["element_guid"] == global_id
    ]


@app.get("/api/results")
def results(status: str | None = Query(default=None)) -> list[dict]:
    all_results = engine.ensure_results()
    if status is None:
        return all_results
    return [result for result in all_results if result["status"] == status]


@app.post("/api/checks/run")
def run_checks() -> dict:
    run_id, new_results = store.run_and_save(engine)
    return {
        "run_id": run_id,
        "execution_id": engine.execution_id,
        "result_count": len(new_results),
        "status_counts": dict(Counter(result["status"] for result in new_results)),
        "results": new_results,
    }


@app.get("/api/scene")
def scene() -> dict:
    return {
        "model_id": MODEL_ID,
        "units": "m",
        "elements": engine.serialised_elements(include_geometry=True),
    }


@app.get("/api/ids/report")
def ids_report() -> dict:
    return engine.ids_report()


@app.get("/api/graph/ego")
def graph_ego(rule_id: str | None = None, element_guid: str | None = None) -> dict:
    if bool(rule_id) == bool(element_guid):
        raise HTTPException(
            status_code=422,
            detail="Provide exactly one of rule_id or element_guid.",
        )
    if rule_id:
        require_rule(rule_id)
    if element_guid:
        require_element(element_guid)
    return ego_graph(engine=engine, rule_id=rule_id, element_guid=element_guid)


@app.get("/")
def index():
    return FileResponse(FRONTEND_PATH / "index.html")


app.mount("/static", StaticFiles(directory=FRONTEND_PATH), name="static")
