from __future__ import annotations

from collections import Counter
from math import ceil
from pathlib import Path
from threading import Lock
from typing import Literal

from fastapi import BackgroundTasks, FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse, Response
from fastapi.staticfiles import StaticFiles

from .engine import CHECKER_VERSION, MODEL_ID, ComplianceEngine
from .exports import bcf_report, csv_report, html_report, json_report
from .graph import ego_graph
from .ifc_adapter import serialise_element
from .imports import MAX_IFC_BYTES, ImportValidationError, ModelImportService
from .nl_query import (
    NaturalLanguageQueryRequest,
    ParsedQuery,
    QueryDSL,
    QueryExecutionResponse,
    execute_query,
    parse_natural_language,
    validate_dsl,
)
from .paths import FRONTEND_PATH, IMPORTS_PATH, MODEL_PATH
from .storage import DEFAULT_PROJECT_ID, ComplianceStore

app = FastAPI(
    title="IFC Bidirectional Compliance MVD",
    version=CHECKER_VERSION,
    description="Traceable exploration from structured IBC rules to IFC elements and back.",
)
SCENE_CHUNK_SIZE = 100
engine = ComplianceEngine()
engine.run(persist=False)
store = ComplianceStore()
store.seed_fixture(
    model_id=MODEL_ID,
    model_name="IBC egress controlled fixture",
    schema_version=engine.model.schema,
    source="reproducibly generated by scripts/generate_fixture.py",
    model_path=engine.model_path,
    element_count=len(engine.elements),
)
store.replace_model_elements(MODEL_ID, engine.serialised_elements(include_geometry=False))
import_service = ModelImportService(store)
engines = {MODEL_ID: engine}
engine_locks: dict[str, Lock] = {}
engine_locks_guard = Lock()


def model_engine_lock(model_id: str) -> Lock:
    with engine_locks_guard:
        return engine_locks.setdefault(model_id, Lock())


def require_model_engine(model_id: str) -> ComplianceEngine:
    cached = engines.get(model_id)
    if cached is not None:
        return cached
    with model_engine_lock(model_id):
        cached = engines.get(model_id)
        if cached is not None:
            return cached
        record = store.get_model(model_id, include_private=True)
        if record is None:
            raise HTTPException(status_code=404, detail=f"Unknown model: {model_id}")
        if record["source_kind"] == "FIXTURE":
            model_path = MODEL_PATH
        else:
            stored_path = record.get("stored_path")
            if not stored_path:
                raise HTTPException(
                    status_code=409,
                    detail="The imported model has no stored asset.",
                )
            import_root = import_service.imports_path.resolve()
            model_path = (import_root / Path(stored_path)).resolve()
            if import_root not in model_path.parents or not model_path.is_file():
                raise HTTPException(
                    status_code=409,
                    detail="The imported model asset is unavailable.",
                )
        loaded = ComplianceEngine(model_path=model_path, model_id=model_id)
        loaded.run(persist=False)
        engines[model_id] = loaded
        return loaded


def require_rule(rule_id: str) -> dict:
    try:
        return engine.rules[rule_id]
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown rule: {rule_id}") from error


def require_element(global_id: str):
    try:
        return engine.elements[global_id]
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown element: {global_id}") from error


@app.get("/api/health")
def health() -> dict:
    return {
        "status": "ok",
        "checker_version": CHECKER_VERSION,
        "model_loaded": True,
        "rule_count": len(engine.rules),
        "element_count": len(engine.elements),
        "storage": {
            "backend": "sqlite",
            "schema_version": store.schema_version(),
        },
    }


@app.get("/api/models")
def models() -> list[dict]:
    return [
        {
            **model,
            "schema": model["schema_version"],
        }
        for model in store.list_models()
    ]


@app.get("/api/projects")
def projects() -> list[dict]:
    return store.list_projects()


@app.post(
    "/api/import-jobs",
    status_code=202,
    openapi_extra={
        "requestBody": {
            "required": True,
            "content": {
                "application/octet-stream": {
                    "schema": {"type": "string", "format": "binary"}
                },
                "application/x-step": {
                    "schema": {"type": "string", "format": "binary"}
                },
            },
        }
    },
)
async def create_import_job(
    request: Request,
    background_tasks: BackgroundTasks,
    filename: str = Query(min_length=1, max_length=255),
    project_id: str = Query(default=DEFAULT_PROJECT_ID, min_length=1, max_length=128),
    source: str = Query(default="local user upload", min_length=1, max_length=500),
    license_name: str = Query(
        default="user-provided; redistribution not granted",
        alias="license",
        min_length=1,
        max_length=200,
    ),
) -> dict:
    content_length = request.headers.get("content-length")
    if content_length:
        try:
            declared_length = int(content_length)
        except ValueError as error:
            raise HTTPException(status_code=400, detail="Invalid Content-Length header.") from error
        if declared_length > MAX_IFC_BYTES:
            raise HTTPException(
                status_code=413,
                detail={
                    "code": "UPLOAD_TOO_LARGE",
                    "message": f"The IFC upload exceeds the {MAX_IFC_BYTES // (1024 * 1024)} MiB limit.",
                },
            )
    chunks = []
    received = 0
    async for chunk in request.stream():
        received += len(chunk)
        if received > MAX_IFC_BYTES:
            raise HTTPException(
                status_code=413,
                detail={
                    "code": "UPLOAD_TOO_LARGE",
                    "message": f"The IFC upload exceeds the {MAX_IFC_BYTES // (1024 * 1024)} MiB limit.",
                },
            )
        chunks.append(chunk)
    try:
        job_id, source_sha256 = import_service.submit(
            payload=b"".join(chunks),
            filename=filename,
            media_type=request.headers.get("content-type"),
            project_id=project_id,
        )
    except ImportValidationError as error:
        raise HTTPException(
            status_code=error.status_code,
            detail={"code": error.code, "message": error.public_message},
        ) from error
    except ValueError as error:
        raise HTTPException(status_code=404, detail=str(error)) from error
    background_tasks.add_task(
        import_service.process,
        job_id,
        source=source,
        license_name=license_name,
    )
    job = store.get_import_job(job_id)
    return {
        **job,
        "source_sha256": source_sha256,
        "poll_url": f"/api/import-jobs/{job_id}",
    }


@app.get("/api/import-jobs")
def import_jobs(
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
) -> dict:
    return store.list_import_jobs(limit=limit, offset=offset)


@app.get("/api/import-jobs/{job_id}")
def import_job(job_id: str) -> dict:
    item = store.get_import_job(job_id)
    if item is None:
        raise HTTPException(status_code=404, detail=f"Unknown import job: {job_id}")
    return item


@app.post("/api/import-jobs/{job_id}/cancel")
def cancel_import_job(job_id: str) -> dict:
    before = store.get_import_job(job_id)
    if before is None:
        raise HTTPException(status_code=404, detail=f"Unknown import job: {job_id}")
    item = store.cancel_import_job(job_id)
    if item["status"] != "CANCELLED":
        raise HTTPException(
            status_code=409,
            detail="Only queued imports can be cancelled safely.",
        )
    return item


@app.get("/api/models/{model_id}/elements")
def model_elements(
    model_id: str,
    ifc_class: str | None = Query(default=None, min_length=1, max_length=64),
    search: str | None = Query(default=None, min_length=1, max_length=200),
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
) -> dict:
    result = store.list_elements(
        model_id,
        ifc_class=ifc_class,
        search=search,
        limit=limit,
        offset=offset,
    )
    if result is None:
        raise HTTPException(status_code=404, detail=f"Unknown model: {model_id}")
    return result


@app.get("/api/check-runs")
def check_runs(
    model_id: str | None = None,
    status: str | None = None,
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
) -> dict:
    return store.list_runs(
        model_id=model_id,
        status=status,
        limit=limit,
        offset=offset,
    )


@app.get("/api/check-runs/{run_id}")
def check_run(run_id: str) -> dict:
    item = store.get_run(run_id)
    if item is None:
        raise HTTPException(status_code=404, detail=f"Unknown check run: {run_id}")
    return item


@app.get("/api/check-runs/{run_id}/export")
def export_check_run(
    run_id: str,
    format: Literal["json", "csv", "html", "bcf"],
    locale: Literal["zh-CN", "en"] = "en",
) -> Response:
    item = store.get_run(run_id)
    if item is None:
        raise HTTPException(status_code=404, detail=f"Unknown check run: {run_id}")
    exporters = {
        "json": (json_report, "application/json", "attachment"),
        "csv": (csv_report, "text/csv; charset=utf-8", "attachment"),
        "html": (
            lambda run: html_report(run, locale=locale),
            "text/html; charset=utf-8",
            "inline",
        ),
        "bcf": (bcf_report, "application/zip", "attachment"),
    }
    exporter, media_type, disposition = exporters[format]
    extension = "bcfzip" if format == "bcf" else format
    filename = f"ifc-compliance-{run_id}.{extension}"
    return Response(
        content=exporter(item),
        media_type=media_type,
        headers={
            "Content-Disposition": f'{disposition}; filename="{filename}"',
            "X-Content-Type-Options": "nosniff",
        },
    )


@app.get("/api/check-runs/{base_run_id}/compare/{target_run_id}")
def compare_check_runs(base_run_id: str, target_run_id: str) -> dict:
    comparison = store.compare_runs(base_run_id, target_run_id)
    if comparison is None:
        raise HTTPException(status_code=404, detail="One or both check runs do not exist.")
    return comparison


@app.post("/api/query/parse", response_model=ParsedQuery)
def parse_query(request: NaturalLanguageQueryRequest) -> ParsedQuery:
    return parse_natural_language(
        request,
        require_model_engine(request.context.model_id or MODEL_ID),
    )


@app.post("/api/query/execute", response_model=QueryExecutionResponse)
def run_natural_language_query(
    request: NaturalLanguageQueryRequest,
) -> QueryExecutionResponse:
    selected_engine = require_model_engine(request.context.model_id or MODEL_ID)
    parsed = parse_natural_language(request, selected_engine)
    response = execute_query(parsed, selected_engine)
    response.query_id = store.save_query(
        original_utterance=parsed.original_utterance,
        locale=parsed.locale,
        dsl=parsed.dsl.model_dump(),
        result_count=response.total,
        warnings=parsed.warnings,
        model_id=selected_engine.model_id,
    )
    return response


@app.post("/api/query/execute-dsl", response_model=QueryExecutionResponse)
def run_structured_query(
    dsl: QueryDSL,
    model_id: str = Query(default=MODEL_ID),
) -> QueryExecutionResponse:
    selected_engine = require_model_engine(model_id)
    parsed = validate_dsl(dsl, selected_engine)
    response = execute_query(parsed, selected_engine)
    response.query_id = store.save_query(
        original_utterance=parsed.original_utterance,
        locale=parsed.locale,
        dsl=dsl.model_dump(),
        result_count=response.total,
        warnings=parsed.warnings,
        model_id=model_id,
    )
    return response


@app.get("/api/queries")
def query_history(
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
) -> dict:
    return store.list_queries(limit=limit, offset=offset)


@app.get("/api/models/{model_id}/elements/{global_id}")
def model_element(model_id: str, global_id: str) -> dict:
    if store.get_model(model_id) is None:
        raise HTTPException(status_code=404, detail=f"Unknown model: {model_id}")
    match = store.get_element(model_id, global_id)
    if match is not None:
        return match
    selected_engine = require_model_engine(model_id)
    try:
        return serialise_element(
            selected_engine.elements[global_id],
            include_geometry=False,
        )
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown element: {global_id}") from error


@app.get("/api/rules")
def rules(model_id: str = Query(default=MODEL_ID)) -> list[dict]:
    selected_engine = require_model_engine(model_id)
    results = selected_engine.ensure_results()
    response = []
    for rule in selected_engine.collection["rules"]:
        counts = Counter(
            result["status"] for result in results if result["rule_id"] == rule["rule_id"]
        )
        response.append({**rule, "status_counts": dict(counts)})
    return response


@app.get("/api/rules/{rule_id}")
def rule(rule_id: str, model_id: str = Query(default=MODEL_ID)) -> dict:
    selected = require_rule(rule_id)
    selected_engine = require_model_engine(model_id)
    return {
        **selected,
        "results": [
            item for item in selected_engine.ensure_results() if item["rule_id"] == rule_id
        ],
    }


@app.get("/api/rules/{rule_id}/elements")
def rule_elements(
    rule_id: str,
    model_id: str = Query(default=MODEL_ID),
) -> list[dict]:
    require_rule(rule_id)
    selected_engine = require_model_engine(model_id)
    by_guid = selected_engine.elements
    return [
        {
            **serialise_element(by_guid[result["element_guid"]]),
            "result": result,
        }
        for result in selected_engine.ensure_results()
        if result["rule_id"] == rule_id
    ]


@app.get("/api/elements/{global_id}/rules")
def element_rules(
    global_id: str,
    model_id: str = Query(default=MODEL_ID),
) -> list[dict]:
    selected_engine = require_model_engine(model_id)
    if global_id not in selected_engine.elements:
        raise HTTPException(status_code=404, detail=f"Unknown element: {global_id}")
    return [
        {**selected_engine.rules[result["rule_id"]], "result": result}
        for result in selected_engine.ensure_results()
        if result["element_guid"] == global_id
    ]


@app.get("/api/elements/{global_id}/results")
def element_results(
    global_id: str,
    model_id: str = Query(default=MODEL_ID),
) -> list[dict]:
    selected_engine = require_model_engine(model_id)
    if global_id not in selected_engine.elements:
        raise HTTPException(status_code=404, detail=f"Unknown element: {global_id}")
    return [
        result
        for result in selected_engine.ensure_results()
        if result["element_guid"] == global_id
    ]


@app.get("/api/results")
def results(
    status: str | None = Query(default=None),
    model_id: str = Query(default=MODEL_ID),
) -> list[dict]:
    all_results = require_model_engine(model_id).ensure_results()
    if status is None:
        return all_results
    return [result for result in all_results if result["status"] == status]


@app.post("/api/checks/run")
def run_checks(model_id: str = Query(default=MODEL_ID)) -> dict:
    selected_engine = require_model_engine(model_id)
    run_id, new_results = store.run_and_save(selected_engine)
    return {
        "run_id": run_id,
        "execution_id": selected_engine.execution_id,
        "model_id": model_id,
        "result_count": len(new_results),
        "status_counts": dict(Counter(result["status"] for result in new_results)),
        "results": new_results,
    }


@app.get("/api/scene")
def scene(model_id: str = Query(default=MODEL_ID)) -> dict:
    selected_engine = require_model_engine(model_id)
    return {
        "model_id": model_id,
        "units": "m",
        "elements": selected_engine.serialised_elements(include_geometry=True),
    }


@app.get("/api/scene/manifest")
def scene_manifest(model_id: str = Query(default=MODEL_ID)) -> dict:
    selected_engine = require_model_engine(model_id)
    total = len(selected_engine.elements)
    return {
        "model_id": model_id,
        "units": "m",
        "ordering": "global_id",
        "total_elements": total,
        "chunk_size": SCENE_CHUNK_SIZE,
        "chunk_count": ceil(total / SCENE_CHUNK_SIZE) if total else 0,
    }


@app.get("/api/scene/chunks/{chunk_index}")
def scene_chunk(
    chunk_index: int,
    model_id: str = Query(default=MODEL_ID),
) -> dict:
    selected_engine = require_model_engine(model_id)
    total = len(selected_engine.elements)
    chunk_count = ceil(total / SCENE_CHUNK_SIZE) if total else 0
    if chunk_index < 0 or chunk_index >= chunk_count:
        raise HTTPException(status_code=404, detail=f"Unknown scene chunk: {chunk_index}")
    offset = chunk_index * SCENE_CHUNK_SIZE
    elements = selected_engine.serialised_elements(
        include_geometry=True,
        offset=offset,
        limit=SCENE_CHUNK_SIZE,
    )
    return {
        "model_id": model_id,
        "units": "m",
        "ordering": "global_id",
        "chunk_index": chunk_index,
        "chunk_count": chunk_count,
        "element_offset": offset,
        "element_count": len(elements),
        "elements": elements,
    }


@app.get("/api/ids/report")
def ids_report(model_id: str = Query(default=MODEL_ID)) -> dict:
    return require_model_engine(model_id).ids_report()


@app.get("/api/graph/ego")
def graph_ego(
    rule_id: str | None = None,
    element_guid: str | None = None,
    model_id: str = Query(default=MODEL_ID),
) -> dict:
    selected_engine = require_model_engine(model_id)
    if bool(rule_id) == bool(element_guid):
        raise HTTPException(
            status_code=422,
            detail="Provide exactly one of rule_id or element_guid.",
        )
    if rule_id:
        require_rule(rule_id)
    if element_guid:
        if element_guid not in selected_engine.elements:
            raise HTTPException(status_code=404, detail=f"Unknown element: {element_guid}")
    return ego_graph(
        engine=selected_engine,
        rule_id=rule_id,
        element_guid=element_guid,
    )


@app.get("/")
def index():
    return FileResponse(FRONTEND_PATH / "index.html")


app.mount("/static", StaticFiles(directory=FRONTEND_PATH), name="static")
