from __future__ import annotations

from collections import Counter

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from .engine import CHECKER_VERSION, MODEL_ID, ComplianceEngine
from .graph import ego_graph
from .ifc_adapter import serialise_element
from .paths import FRONTEND_PATH

app = FastAPI(
    title="IFC Bidirectional Compliance MVD",
    version=CHECKER_VERSION,
    description="Traceable exploration from structured IBC rules to IFC elements and back.",
)
engine = ComplianceEngine()
engine.run(persist=False)


def require_rule(rule_id: str) -> dict:
    try:
        return engine.rules[rule_id]
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown rule: {rule_id}") from error


def require_element(global_id: str):
    try:
        return engine.elements[global_id]
    except KeyError as error:
        raise HTTPException(status_code=404, detail=f"Unknown element: {global_id}") from error


@app.get("/api/health")
def health() -> dict:
    return {
        "status": "ok",
        "checker_version": CHECKER_VERSION,
        "model_loaded": True,
        "rule_count": len(engine.rules),
        "element_count": len(engine.elements),
    }


@app.get("/api/models")
def models() -> list[dict]:
    return [
        {
            "model_id": MODEL_ID,
            "name": "IBC egress controlled fixture",
            "schema": engine.model.schema,
            "element_count": len(engine.elements),
            "source": "reproducibly generated by scripts/generate_fixture.py",
        }
    ]


@app.get("/api/models/{model_id}/elements/{global_id}")
def model_element(model_id: str, global_id: str) -> dict:
    if model_id != MODEL_ID:
        raise HTTPException(status_code=404, detail=f"Unknown model: {model_id}")
    return serialise_element(require_element(global_id), include_geometry=False)


@app.get("/api/rules")
def rules() -> list[dict]:
    results = engine.ensure_results()
    response = []
    for rule in engine.collection["rules"]:
        counts = Counter(
            result["status"] for result in results if result["rule_id"] == rule["rule_id"]
        )
        response.append({**rule, "status_counts": dict(counts)})
    return response


@app.get("/api/rules/{rule_id}")
def rule(rule_id: str) -> dict:
    selected = require_rule(rule_id)
    return {
        **selected,
        "results": [item for item in engine.ensure_results() if item["rule_id"] == rule_id],
    }


@app.get("/api/rules/{rule_id}/elements")
def rule_elements(rule_id: str) -> list[dict]:
    require_rule(rule_id)
    by_guid = engine.elements
    return [
        {
            **serialise_element(by_guid[result["element_guid"]]),
            "result": result,
        }
        for result in engine.ensure_results()
        if result["rule_id"] == rule_id
    ]


@app.get("/api/elements/{global_id}/rules")
def element_rules(global_id: str) -> list[dict]:
    require_element(global_id)
    return [
        {**engine.rules[result["rule_id"]], "result": result}
        for result in engine.ensure_results()
        if result["element_guid"] == global_id
    ]


@app.get("/api/elements/{global_id}/results")
def element_results(global_id: str) -> list[dict]:
    require_element(global_id)
    return [
        result
        for result in engine.ensure_results()
        if result["element_guid"] == global_id
    ]


@app.get("/api/results")
def results(status: str | None = Query(default=None)) -> list[dict]:
    all_results = engine.ensure_results()
    if status is None:
        return all_results
    return [result for result in all_results if result["status"] == status]


@app.post("/api/checks/run")
def run_checks() -> dict:
    new_results = engine.run(persist=True)
    return {
        "execution_id": engine.execution_id,
        "result_count": len(new_results),
        "status_counts": dict(Counter(result["status"] for result in new_results)),
        "results": new_results,
    }


@app.get("/api/scene")
def scene() -> dict:
    return {
        "model_id": MODEL_ID,
        "units": "m",
        "elements": engine.serialised_elements(include_geometry=True),
    }


@app.get("/api/ids/report")
def ids_report() -> dict:
    return engine.ids_report()


@app.get("/api/graph/ego")
def graph_ego(rule_id: str | None = None, element_guid: str | None = None) -> dict:
    if bool(rule_id) == bool(element_guid):
        raise HTTPException(
            status_code=422,
            detail="Provide exactly one of rule_id or element_guid.",
        )
    if rule_id:
        require_rule(rule_id)
    if element_guid:
        require_element(element_guid)
    return ego_graph(engine=engine, rule_id=rule_id, element_guid=element_guid)


@app.get("/")
def index():
    return FileResponse(FRONTEND_PATH / "index.html")


app.mount("/static", StaticFiles(directory=FRONTEND_PATH), name="static")

